// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserDic;

namespace UserDicionary.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("UserDic.customDic", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("classification");

                    b.Property<string>("translation");

                    b.Property<string>("userName");

                    b.Property<string>("word");

                    b.Property<int>("yesorNo");

                    b.HasKey("id");

                    b.ToTable("customDics");
                });

            modelBuilder.Entity("UserDic.passage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("remainWords");

                    b.Property<string>("url");

                    b.HasKey("id");

                    b.ToTable("passages");
                });

            modelBuilder.Entity("UserDic.user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("password");

                    b.Property<string>("remainWords_1");

                    b.Property<string>("remainWords_2");

                    b.Property<string>("userName");

                    b.HasKey("id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
